---
title: "Things About Me"
output: html_document
---

# Name
**Junjie Hu**

# Skills

**Language:** English, Mandarin

**Computer Skills:** SAS 9.4, R studio, Minitab, Microsoft Office (Excel, PowerPoint, Word)

**Lab Skills:** gel electrophoresis, PCR, CRISPR-Cas9, western blot, cloning, restriction enzyme digestion.

# Education

**Columbia University**

Master of Public Health, Major: Epidemiology, Certificate: Advanced Epi

Current GPA: 4.03/4.00 

Core Courses: Epidemiology, SAS Statistical Computing, Applied Regression, Data Science (R)


**University of California San Diego**

Bachelor of Science, Major: General Biology 

GPA: 3.83 (Cum Laude) 

Awards: Distinction in Biology Division, UCSD Phi Beta Kappa, Warren College Provost honors


# Research and Work Experiences

**Los Angeles County, Department of Public Health, Division of HIV and STD Programs**

  * Analyzed with raw HIV and STD Testing Services (HTS) dataset of over 5 million data points utilizing SAS 9.4
  
  * Developed project Sociodemographic Factors Associated with Pre-exposure Prophylaxis (PrEP) Refusal
  
  * Conducted comprehensive literature review, recoded variables, performed descriptive statistic tables, implemented multilevel GLIMMIX regression analysis, and drafted scientific manuscript
  
  * Created summary tables for 2022 Los Angeles County HIV Surveillance Annual Report
  
  * Collaborated with a multidisciplinary team and presented findings to the team
  
**Columbia University Research Fellowship**

  * Processed Longitudinal Research on Aging Drivers dataset with over 9 million data points utilizing SAS

  * Examined Association between Trait Anger and Driving Safety among Older Adult Drivers through SAS
  
  * Review comprehensive literatures, clean dataset, analyze bivariate analysis, and generate GEE longitudinal regression analysis.
  
**UCSD Senior Honor Program**

  * Investigated the roles of Gretchen Hagen 3 (GH3) Group III genes in hormone homeostasis and plant
development

  * Constructed CRISPR-Cas9 vectors to knockout the GH3 genes and confirmed genotype

  * Published thesis “Roles of the Group III GRETCHEN HAGEN 3 (GH3) genes in hormone homeostasis and plant development” on Saltman Quarterly Journal
